//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class dvd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dvd()
        {
            this.loan = new HashSet<loan>();
        }
    
        public byte id { get; set; }
        [Required]
        [Display(Name = "Copy Number")]
        public string copy_number { get; set; }

        [Required]
        [Display(Name = "Title")]
        public string title { get; set; }

        [Required]
        [Display(Name = "Released Date")]
        public System.DateTime released_date { get; set; }

        [Required]
        [Display(Name = "Genres")]
        public byte genres_id { get; set; }

        [Required]
        [Display(Name = "Stock")]
        public int stock { get; set; }

        [Required]
        [Display(Name = "Date Added")]
        public System.DateTime date_added { get; set; }

        [Required]
        [Display(Name = "Studio")]
        public byte studio_id { get; set; }

        [Required]
        [Display(Name = "Producer")]
        public Nullable<byte> producer_id { get; set; }

        [Required]
        [Display(Name = "Cast")]
        public Nullable<byte> cast_id { get; set; }

        [Required]
        [Display(Name = "Cover")]
        public string cover { get; set; }
    
        public virtual cast cast { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual producer producer { get; set; }
        public virtual studio studio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loan> loan { get; set; }
    }
}
