//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class loan
    {
        public byte id { get; set; }

        [Required]
        [Display(Name = "Date Out")]
        public System.DateTime date_out { get; set; }

        [Required]
        [Display(Name = "Amount Paid")]
        public int amount_paid { get; set; }

        public Nullable<int> due { get; set; }

        public Nullable<System.DateTime> date_returned { get; set; }

        public Nullable<int> penalty_charge { get; set; }

        [Required]
        [Display(Name = "Dvd")]
        public Nullable<byte> dvd_id { get; set; }

        [Required]
        [Display(Name = "Member")]
        public Nullable<byte> member_id { get; set; }

        [Required]
        [Display(Name = "Loan Status")]
        public Nullable<byte> loan_status_id { get; set; }

        [Required]
        [Display(Name = "Number of copies")]
        public Nullable<int> num_copy { get; set; }
    
        public virtual dvd dvd { get; set; }
        public virtual member member { get; set; }
        public virtual loan_status loan_status { get; set; }
    }
}
