//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public member()
        {
            this.loan = new HashSet<loan>();
        }
    
        public byte id { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string first_name { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string last_name { get; set; }

        [Required, DataType(DataType.EmailAddress)]
        [Display(Name = "Email Address")]
        public string email_address { get; set; }

        public string address { get; set; }

        [MaxLength(10)]
        public string phone { get; set; }

        [Required]
        [Display(Name = "Date of Birth")]
        public Nullable<System.DateTime> dob { get; set; }

        [Required, MaxLength(10)]
        [Display(Name = "Password")]
        public string password { get; set; }

        public string profile { get; set; }

        public Nullable<byte> mem_Cat_Id { get; set; }

        [Required]
        [Display(Name = "Role")]
        public byte role_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loan> loan { get; set; }
        public virtual member_category member_category { get; set; }
        public virtual roles roles { get; set; }
    }
}
