//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EverestDvdEntities : DbContext
    {
        public EverestDvdEntities()
            : base("name=EverestDvdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cast> cast { get; set; }
        public virtual DbSet<dvd> dvd { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<loan> loan { get; set; }
        public virtual DbSet<loan_status> loan_status { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<member_category> member_category { get; set; }
        public virtual DbSet<producer> producer { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<studio> studio { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
