//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class producer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producer()
        {
            this.dvd = new HashSet<dvd>();
        }
    
        public byte id { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string first_name { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string last_name { get; set; }

        [Required]
        [Display(Name = "Date of Birth")]
        public System.DateTime dob { get; set; }

        [Required]
        [Display(Name = "Movies Produced")]
        public int movies_produced { get; set; }

        [Required]
        [Display(Name = "Net Worth")]
        public int net_worth { get; set; }

        [Required]
        [Display(Name = "About")]
        public string about { get; set; }

        [Required]
        [Display(Name = "Profile")]
        public string profile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dvd> dvd { get; set; }
    }
}
